version: 0.2
env:
  shell: /bin/bash
  parameter-store: 
    BUCKET_NAME_PREFIX: /development/build/BUCKET_NAME_PREFIX 
    BUCKET_KEY_PREFIX: /development/build/BUCKET_KEY_PREFIX

batch:
  fast-fail: false
  build-graph:
    - identifier: checks
      ignore-failure: false
      buildspec: build/checks.yml
    - identifier: deploy
      ignore-failure: false
      depend-on:
        - checks
      buildspec: build/deploy.yml

phases:
  build:
    on-failure: ABORT
    commands:
      - echo "Actual build steps are done in the build graph."

